// God of Thunder - SGDK 1.70 Resource Descriptor
// Auto-generated by convert_assets.py + updated by pack_assets.py

// ── Binary level data (from SDAT1-3, 120 levels × 512 bytes each) ─────────────
BIN level_data_ep1  "res/level_data_ep1.bin"
BIN level_data_ep2  "res/level_data_ep2.bin"
BIN level_data_ep3  "res/level_data_ep3.bin"

// ── Actor ROM data (114 × 5200 bytes, ID-indexed) ─────────────────────────────
BIN actor_rom_data  "res/actor_rom_data.bin"

// ── Background Tilesets (230 × 16×16 tiles, 4bpp, PAL0) ──────────────────────
TILESET bg_tiles_ep1   "res/bg_tiles_ep1.png"   BEST  0
TILESET bg_tiles_ep2   "res/bg_tiles_ep2.png"   BEST  0
TILESET bg_tiles_ep3   "res/bg_tiles_ep3.png"   BEST  0

// ── Object / pickup tiles (32 × 16×16, 4bpp, PAL0) ───────────────────────────
TILESET obj_tiles      "res/objects.png"         BEST  0

// ── Sprites (2×2 VDP tiles = 16×16 px per frame, 4 dirs × 4 frames) ──────────
SPRITE thor_spr    "res/thor.png"    2 2  BEST  0
SPRITE hammer_spr  "res/hammer.png"  2 2  BEST  0
SPRITE fx_spr      "res/fx.png"      2 2  BEST  0
SPRITE enemy_spr   "res/enemies.png" 2 2  BEST  0
SPRITE npc_spr     "res/npcs.png"    2 2  BEST  0

// ── Placeholder music/SFX (add real XGM/WAV files here) ──────────────────────
// XGM  music_track_0  "res/music_forest.xgm"
// XGM  music_track_1  "res/music_cave.xgm"
// XGM  music_track_2  "res/music_castle.xgm"
// XGM  music_track_3  "res/music_boss.xgm"
// XGM  music_track_4  "res/music_town.xgm"
// XGM  music_track_5  "res/music_final.xgm"
// WAV  sfx_ow         "res/sfx/ow.wav"     XGM
// (add the remaining 18 SFX entries following the same pattern)
