// res/resources.h - Auto-generated by rescomp from res/resources.res
// This file is regenerated on every build. Do not edit manually.
#pragma once
#include <genesis.h>

// BIN resources
extern const u8  level_data_ep1[];
extern const u32 level_data_ep1_size;
extern const u8  level_data_ep2[];
extern const u32 level_data_ep2_size;
extern const u8  level_data_ep3[];
extern const u32 level_data_ep3_size;
extern const u8  actor_rom_data[];
extern const u32 actor_rom_data_size;

// TILESET resources
extern const TileSet bg_tiles_ep1;
extern const TileSet bg_tiles_ep2;
extern const TileSet bg_tiles_ep3;
extern const TileSet obj_tiles;

// SPRITE resources
extern const SpriteDefinition thor_spr;
extern const SpriteDefinition hammer_spr;
extern const SpriteDefinition fx_spr;
extern const SpriteDefinition enemy_spr;
extern const SpriteDefinition npc_spr;
