// God of Thunder - Genesis Hardware Palettes
// Auto-generated by convert_assets.py  (v2 - correct 8-bit palette)
// Format: 0x0BGR  (Genesis native, 9-bit: 3 bits per channel)
// Slot 0 in every palette = transparent (never rendered by VDP)

#ifndef PALETTE_GEN_H
#define PALETTE_GEN_H

#include <genesis.h>

// Background / environment tiles (BPICS)
static const u16 got_pal_bg[16] = {
    0x0000,  /* #000000 */
    0x00A0,  /* #00b600 */
    0x0080,  /* #009200 */
    0x0024,  /* #492400 */
    0x0040,  /* #004900 */
    0x0022,  /* #242400 */
    0x046A,  /* #b66d49 */
    0x048C,  /* #db9249 */
    0x0060,  /* #006d00 */
    0x0244,  /* #494924 */
    0x0C60,  /* #006ddb */
    0x048E,  /* #ff9249 */
    0x0E00,  /* #0000ff */
    0x0048,  /* #924900 */
    0x006E,  /* #ff6d00 */
    0x0222,  /* #242424 */
};

// Thor, Hammer, FX (sparkle, explosion)
static const u16 got_pal_thor[16] = {
    0x0000,  /* #000000 */
    0x0222,  /* #242424 */
    0x0044,  /* #494900 */
    0x000E,  /* #ff0000 */
    0x0088,  /* #929200 */
    0x000C,  /* #db0000 */
    0x0AAA,  /* #b6b6b6 */
    0x0248,  /* #924924 */
    0x0CCC,  /* #dbdbdb */
    0x0888,  /* #929292 */
    0x0666,  /* #6d6d6d */
    0x00CE,  /* #ffdb00 */
    0x0006,  /* #6d0000 */
    0x000A,  /* #b60000 */
    0x00CC,  /* #dbdb00 */
    0x0066,  /* #6d6d00 */
};

// Enemies and shot projectiles
static const u16 got_pal_enemy[16] = {
    0x0000,  /* #000000 */
    0x0222,  /* #242424 */
    0x0666,  /* #6d6d6d */
    0x000E,  /* #ff0000 */
    0x0CCC,  /* #dbdbdb */
    0x0888,  /* #929292 */
    0x000C,  /* #db0000 */
    0x0444,  /* #494949 */
    0x0AAA,  /* #b6b6b6 */
    0x0248,  /* #924924 */
    0x0024,  /* #492400 */
    0x048E,  /* #ff9249 */
    0x08AE,  /* #ffb692 */
    0x046A,  /* #b66d49 */
    0x00EE,  /* #ffff00 */
    0x000A,  /* #b60000 */
};

// NPCs, pickup objects, HUD
static const u16 got_pal_npc[16] = {
    0x0000,  /* #000000 */
    0x0222,  /* #242424 */
    0x046A,  /* #b66d49 */
    0x048E,  /* #ff9249 */
    0x08AE,  /* #ffb692 */
    0x0666,  /* #6d6d6d */
    0x0AAA,  /* #b6b6b6 */
    0x048C,  /* #db9249 */
    0x068E,  /* #ff926d */
    0x0CCC,  /* #dbdbdb */
    0x0888,  /* #929292 */
    0x0ACE,  /* #ffdbb6 */
    0x0248,  /* #924924 */
    0x0444,  /* #494949 */
    0x06AE,  /* #ffb66d */
    0x046C,  /* #db6d49 */
};

static inline void got_load_all_palettes(void) {
    PAL_setPalette(PAL0, got_pal_bg,    DMA);
    PAL_setPalette(PAL1, got_pal_thor,  DMA);
    PAL_setPalette(PAL2, got_pal_enemy, DMA);
    PAL_setPalette(PAL3, got_pal_npc,   DMA);
}

#endif // PALETTE_GEN_H
