// God of Thunder - Genesis Hardware Palettes
// Auto-generated by convert_assets.py  (v2 - correct 8-bit palette)
// Format: 0x0BGR  (Genesis native, 9-bit: 3 bits per channel)
// Slot 0 in every palette = transparent (never rendered by VDP)

#ifndef PALETTE_GEN_H
#define PALETTE_GEN_H

#include <genesis.h>

// Background / environment tiles (BPICS)
extern u16 got_pal_bg[16];  // defined in globals.c, slot 0 = bg transparent color

// Thor, Hammer, FX (sparkle, explosion)
static const u16 got_pal_thor[16] = {
    0x0000,  /* #000000 */
    0x0222,  /* #242424 */
    0x0044,  /* #494900 */
    0x000E,  /* #ff0000 */
    0x0088,  /* #929200 */
    0x000C,  /* #db0000 */
    0x0AAA,  /* #b6b6b6 */
    0x0248,  /* #924924 */
    0x0CCC,  /* #dbdbdb */
    0x0888,  /* #929292 */
    0x0666,  /* #6d6d6d */
    0x00CE,  /* #ffdb00 */
    0x0006,  /* #6d0000 */
    0x000A,  /* #b60000 */
    0x00CC,  /* #dbdb00 */
    0x0066,  /* #6d6d00 */
};

// Enemies and shot projectiles
static const u16 got_pal_enemy[16] = {
    0x0000,  /* #000000 */
    0x0222,  /* #242424 */
    0x0666,  /* #6d6d6d */
    0x000E,  /* #ff0000 */
    0x0CCC,  /* #dbdbdb */
    0x0888,  /* #929292 */
    0x000C,  /* #db0000 */
    0x0444,  /* #494949 */
    0x0AAA,  /* #b6b6b6 */
    0x0248,  /* #924924 */
    0x0024,  /* #492400 */
    0x048E,  /* #ff9249 */
    0x08AE,  /* #ffb692 */
    0x046A,  /* #b66d49 */
    0x00EE,  /* #ffff00 */
    0x000A,  /* #b60000 */
};

// NPCs, pickup objects, HUD
static const u16 got_pal_npc[16] = {
    0x0000,  /* #000000 */
    0x0222,  /* #242424 */
    0x046A,  /* #b66d49 */
    0x048E,  /* #ff9249 */
    0x08AE,  /* #ffb692 */
    0x0666,  /* #6d6d6d */
    0x0AAA,  /* #b6b6b6 */
    0x048C,  /* #db9249 */
    0x068E,  /* #ff926d */
    0x0CCC,  /* #dbdbdb */
    0x0888,  /* #929292 */
    0x0ACE,  /* #ffdbb6 */
    0x0248,  /* #924924 */
    0x0444,  /* #494949 */
    0x06AE,  /* #ffb66d */
    0x046C,  /* #db6d49 */
};

static inline void got_load_all_palettes(void) {
    PAL_setPalette(PAL0, got_pal_bg,    DMA);
    PAL_setPalette(PAL1, got_pal_thor,  DMA);
    PAL_setPalette(PAL2, got_pal_enemy, DMA);
    PAL_setPalette(PAL3, got_pal_npc,   DMA);
}


// ─── Background tile transparency fix ────────────────────────────────────────
// On Genesis BG planes, palette slot 0 renders as a solid color (not transparent).
// The original DOS blitter skipped 'transparent' pixels (VGA index 0), showing
// the bg_color tile underneath. We replicate this by setting PAL0 slot 0 to match
// the bg_color tile's dominant color before drawing each level.
// This table maps bg_color tile index → which PAL0 slot holds its main color.
static const u8 bg_tile_transparent_slot[230] = {
    15,  2, 14,  7, 14, 12,  9,  7, 11, 11,  7, 15,  9, 14, 13,  9,
     6,  7, 11, 11,  9,  6,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10,
    10, 10, 10, 10, 10, 10,  6,  8, 10, 10, 10,  7,  7,  9,  7, 15,
    11, 11,  6, 11,  6, 11, 11, 11, 11, 11,  4,  1,  1,  1,  4,  4,
     9,  4,  4,  4,  1,  7, 11,  1, 13,  6,  6,  6,  6,  6, 13, 13,
    13,  7,  6,  7,  9,  6,  7,  7,  6,  7,  7,  7,  7, 11, 14, 13,
    11, 11, 12, 12, 12, 10, 10, 10,  1, 10, 12, 10, 10, 10, 12, 12,
    15, 12, 15, 12, 10,  1, 10,  5, 12, 10,  9, 13, 13,  9, 13,  9,
     9, 13, 14, 13,  9,  9, 14, 13,  9,  9, 13,  5,  6,  6,  7,  7,
    11,  7, 14,  7,  7,  7,  7, 14, 14, 14,  9, 14, 14, 14,  3,  3,
     9,  9,  9,  9,  9, 11, 11, 11, 11, 11, 11, 11, 11,  6, 11,  1,
     1,  2,  7,  7, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
     8,  2,  8,  2,  8,  1,  8,  1, 11,  9,  7, 11, 11, 14,  3, 14,
     3, 12, 13, 11, 11, 11,  0,  4,  0,  0,  6,  6, 15, 15, 15, 15,
    15, 15, 15, 15,  9,  9,
};

// Call this after loading scrn.bg_color to make transparent bg-tile pixels
// show the correct background fill color instead of black.
static inline void got_set_bg_transparent_color(u8 bg_color_tile) {
    u8 slot = (bg_color_tile < 230) ? bg_tile_transparent_slot[bg_color_tile] : 1;
    // Update both the runtime palette AND the palette array so fade_in picks it up
    got_pal_bg[0] = got_pal_bg[slot];
    PAL_setColor(0, got_pal_bg[slot]);
}

#endif // PALETTE_GEN_H
