// God of Thunder - Genesis Hardware Palettes
// Auto-generated by convert_assets.py  (v2 - correct 8-bit palette)
// Format: 0x0BGR  (Genesis native, 9-bit: 3 bits per channel)
// Slot 0 in every palette = transparent (never rendered by VDP)

#ifndef PALETTE_GEN_H
#define PALETTE_GEN_H

#include <genesis.h>

// Background / environment tiles (BPICS)
static const u16 got_pal_bg[16] = {
    0x0000,  /* #000000 */
    0x0005,  /* #b60000 */
    0x0777,  /* #ffffff */
    0x0012,  /* #492400 */
    0x0111,  /* #242424 */
    0x0235,  /* #b66d49 */
    0x0700,  /* #0000ff */
    0x0020,  /* #004900 */
    0x0123,  /* #6d4924 */
    0x0124,  /* #924924 */
    0x0122,  /* #494924 */
    0x0246,  /* #db9249 */
    0x0011,  /* #242400 */
    0x0037,  /* #ff6d00 */
    0x0024,  /* #924900 */
    0x0135,  /* #b66d24 */
};

// Thor, Hammer, FX (sparkle, explosion)
static const u16 got_pal_thor[16] = {
    0x0000,  /* #000000 */
    0x0777,  /* #ffffff */
    0x0111,  /* #242424 */
    0x0022,  /* #494900 */
    0x0007,  /* #ff0000 */
    0x0044,  /* #929200 */
    0x0006,  /* #db0000 */
    0x0555,  /* #b6b6b6 */
    0x0124,  /* #924924 */
    0x0666,  /* #dbdbdb */
    0x0444,  /* #929292 */
    0x0333,  /* #6d6d6d */
    0x0067,  /* #ffdb00 */
    0x0003,  /* #6d0000 */
    0x0005,  /* #b60000 */
    0x0066,  /* #dbdb00 */
};

// Enemies and shot projectiles
static const u16 got_pal_enemy[16] = {
    0x0000,  /* #000000 */
    0x0777,  /* #ffffff */
    0x0111,  /* #242424 */
    0x0333,  /* #6d6d6d */
    0x0007,  /* #ff0000 */
    0x0666,  /* #dbdbdb */
    0x0444,  /* #929292 */
    0x0006,  /* #db0000 */
    0x0222,  /* #494949 */
    0x0555,  /* #b6b6b6 */
    0x0124,  /* #924924 */
    0x0012,  /* #492400 */
    0x0247,  /* #ff9249 */
    0x0457,  /* #ffb692 */
    0x0235,  /* #b66d49 */
    0x0077,  /* #ffff00 */
};

// NPCs, pickup objects, HUD
static const u16 got_pal_npc[16] = {
    0x0000,  /* #000000 */
    0x0111,  /* #242424 */
    0x0777,  /* #ffffff */
    0x0235,  /* #b66d49 */
    0x0247,  /* #ff9249 */
    0x0457,  /* #ffb692 */
    0x0333,  /* #6d6d6d */
    0x0555,  /* #b6b6b6 */
    0x0246,  /* #db9249 */
    0x0347,  /* #ff926d */
    0x0666,  /* #dbdbdb */
    0x0444,  /* #929292 */
    0x0567,  /* #ffdbb6 */
    0x0124,  /* #924924 */
    0x0222,  /* #494949 */
    0x0357,  /* #ffb66d */
};

static inline void got_load_all_palettes(void) {
    PAL_setPalette(PAL0, got_pal_bg,    DMA);
    PAL_setPalette(PAL1, got_pal_thor,  DMA);
    PAL_setPalette(PAL2, got_pal_enemy, DMA);
    PAL_setPalette(PAL3, got_pal_npc,   DMA);
}

#endif // PALETTE_GEN_H
